# Generated by Django 5.1.6 on 2025-02-27 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0002_brand_alter_bike_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='bike',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='bikes/'),
        ),
        migrations.AddField(
            model_name='bike',
            name='plate',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
